[package]
name = "shell"
version = "0.1.0"
authors = ["Daichi Hirono <hidachinoiro@gmail.com>"]

[[bin]]
name = "pgtest"
path = "src/pgtest.rs"

[[bin]]
name = "raw_lib_test"
path = "src/raw_lib_test.rs"

[[bin]]
name = "terminal_test"
path = "src/terminal_test.rs"

[dependencies]
libc = "0.2"
errno = "*"
