[package]
name = "shell"
version = "0.1.0"
authors = ["Daichi Hirono <hidachinoiro@gmail.com>"]

[[bin]]
name = "runtest"
path = "src/runtest.rs"

[dependencies]
errno = "*"
lazy_static = "1.0"
libc = "0.2"
